site_name: Mathy
site_description: Reinforcement learning environment for working with Math

repo_name: justindujardin/mathy
repo_url: https://github.com/justindujardin/mathy
edit_uri: "edit/master/docs/"

nav:
  - Mathy: "index.md"
  - Computer Algebra Software:
      - Overview: "cas/overview.md"
      - Tokenizer: "cas/tokenizer.md"
      - Parser: "cas/parser.md"
      - Transformation Rules:
          - Overview: "cas/rules/overview.md"
          - Associative Swap: "cas/rules/associative_property.md"
          - Commutative Swap: "cas/rules/commutative_property.md"
          - Distributive Factor: "cas/rules/distributive_property_factor_out.md"
          - Distributive Multiply: "cas/rules/distributive_property_multiply_across.md"
          - Variable Multiply: "cas/rules/variable_multiplication.md"
          - Constant Arithmetic: "cas/rules/constant_arithmetic.md"
  - Environments:
      - Polynomials - Combine Terms: "envs/polynomial_combine.md"
      - Polynomials - Complex Terms: "envs/polynomial_complex.md"
  - Machine Learning:
      - Overview: "ml/overview.md"
      - Reinforcement Learning: "ml/reinforcement_learning.md"
      - Monte Carlo Tree Search: "ml/monte_carlo_tree_search.md"

theme:
  name: "material"
  logo: "img/logo_white.svg"
  favicon: "img/favicon.png"
  palette:
    primary: "deep-purple"
    accent: "orange"
  highlightjs: true
  hljs_languages:
    - python
    - typescript

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences
