site_name: Mathy
site_description: Reinforcement learning environment for working with Math

repo_name: justindujardin/mathy
repo_url: https://github.com/justindujardin/mathy
edit_uri: "edit/master/docs/"

nav:
  - Mathy: "index.md"
  - Computer Algebra Software:
      - Overview: "cas/overview.md"
      - Tokenizer: "cas/tokenizer.md"
      - Parser: "cas/parser.md"
  - Transformation Rules:
      - Overview: "rules/overview.md"
      - Associative Swap: "rules/associative_property.md"
      - Commutative Swap: "rules/commutative_property.md"
      - Distributive Factor Out: "rules/distributive_property_factor_out.md"
      - Distributive Multiply: "rules/distributive_property_multiply_across.md"
      - Variable Multiply: "rules/variable_multiplication.md"
      - Constant Arithmetic: "rules/constant_arithmetic.md"
  - Environments:
      - Overview: "envs/overview.md"
      - Combine Like Terms: "envs/polynomial_combine.md"
      - Simplify Complex Terms: "envs/polynomial_complex.md"
      - Binomial Distributive Multiply : "envs/binomial_distribution.md"
  - Machine Learning:
      - Overview: "ml/overview.md"
      - Math Embeddings: "ml/math_embeddings.md"
      - Reinforcement Learning: "ml/reinforcement_learning.md"
      - Monte Carlo Tree Search: "ml/monte_carlo_tree_search.md"
  - About: "about.md"

theme:
  name: "material"
  logo: "img/logo_white.svg"
  favicon: "img/favicon.png"
  palette:
    primary: "deep-orange"
    accent: "orange"
  highlightjs: true
  hljs_languages:
    - python
    - typescript

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences
  - pymdownx.details
