name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Packages
        run: sh tools/ci-setup.sh
      - name: Build Packages
        run: sh tools/build.sh
      - name: Test Packages
        run: sh tools/test.sh
      - name: Report Code Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: sh tools/codecov.sh
