name: Release

on:
  push:
    branches:
      - refs/tags/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Packages
        run: sh tools/ci-setup.sh
      - name: Build Packages
        run: sh tools/build.sh
      - name: Test Packages
        run: sh tools/test.sh
      - name: Report Code Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: sh tools/codecov.sh
      - name: Deploy
        env:
          GH_BRANCH: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: sh tools/deploy_packages.sh
